### ISSUE TITLE
Programs using libs and built after 52bfbdb404 crash when using pre-52bfbdb404 clibs

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/toolchain#388] opened 2022-06-03 07:37 UTC
**Repro:**
- Install [clibs 9.2.2](https://github.com/CE-Programming/libraries/releases/download/v9.2.2/clibs.8xg) for instance (since that's the most popular recent one, but with [10.0 clibs](https://github.com/CE-Programming/libraries/releases/download/v10.0/clibs.8xg) it also crashes)
- Try any program (using a library), built with toolchain at least at 52bfbdb4046aa22912ceb436aa30077c995055e9 ("ensure the libload library is loaded first to check versions") as that's the first bad commit from a quick bisect
- It resets the calc

**Notes:**
- Doesn't crash if you use clibs from 52bfbdb4046aa22912ceb436aa30077c995055e9 or later
- Happens with and without LTO
- CEmu doesn't print anything in the console when it resets

<hr>

WIth clibs earlier than 52bfbdb4046aa22912ceb436aa30077c995055e9 it's fine and displays the usual screen:

![image](https://user-images.githubusercontent.com/660896/171808199-205e632c-5f8c-40fe-8640-577f1e935956.png)

**Comment by adriweb** [comment] 2022-06-03 07:38
Assigning @mateoconlechuga as per the bisect

**Comment by mateoconlechuga** [comment] 2022-06-03 11:20
The issue is that libload is being marked as optional, even though this is the command delivered to the linker:

> fasmg -v1 '/home/hew/CEdev/meta/ld.alm' -i 'DEBUG := 0' -i 'HAS_PRINTF := 1' -i 'HAS_LIBC := 1' -i 'HAS_LIBCXX := 1' -i 'PREFER_OS_CRT := 0' -i 'PREFER_OS_LIBC := 1' -i 'include "/home/hew/CEdev/meta/linker_script"' -i 'range .bss $D052C6 : $D13FD8' -i 'provide __stack = $D1A87E' -i 'locate .header at $D1A87F' -i map -i 'source "obj/icon.src", "/home/hew/CEdev/lib/crt/crt0.src", "obj/lto.src"' -i 'library "/home/hew/CEdev/lib/libload/libload.lib", "/home/hew/CEdev/lib/libload/fileioc.lib", "/home/hew/CEdev/lib/libload/keypadc.lib", "/home/hew/CEdev/lib/libload/graphx.lib", "/home/hew/CEdev/lib/libload/fontlibc.lib"'  bin/DEMO.bin

**Closed** 2022-06-03 22:08 UTC
Labels: bug
