### ISSUE TITLE
"error in backend: unable to legalize instruction" when compiling with -O3 

### ISSUE THREAD

**Issue by Zaalan3** [CE-Programming/toolchain#417] opened 2022-11-19 03:41 UTC
Ran into the following error when compiling using -O3 flag (problem also occurs when using -O2 and -Ofast). 

```
[compiling] src\image.c
[compiling] src\level.c
fatal error: error in backend: unable to legalize instruction: %224:_(s48) = G_LSHR %222:_, %225:_(s8) (in function: loadLevel)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: C:\\CEdev\\bin\\ez80-clang.exe -S -MD -nostdinc -isystem C:\\CEdev\\include -Isrc -fno-threadsafe-statics -Xclang -fforce-mangle-main-argc-argv -mllvm -profile-guided-section-prefix=false -DNDEBUG -g0 -Wall -Wextra -O2 src/level.c -o obj/src/level.c.src
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'src/level.c'.
4.      Running pass 'Legalizer' on function '@loadLevel'
0x7641E062 (0xE0000046 0x00000000 0x00000000 0x00000000), RaiseException() + 0x62 bytes(s)
0x005A0526 (0x040A0100 0x00000000 0x00000020 0x00000013)
0x01000000 (0x00000000 0x00000020 0x00000013 0x0000000A)
0x040A0100 (0x00000020 0x00000013 0x0000000A 0x0000000A) <unknown module>
ez80-clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 15.0.0 (https://github.com/jacobly0/llvm-project 6d9aa7a16db70f3d02ae304b08d4a03011281fef)
Target: ez80
Thread model: posix
InstalledDir: C:\CEdev\bin
```
Source and Debug Output attached. 
[bugsrc.zip](https://github.com/CE-Programming/toolchain/files/10045988/bugsrc.zip)

**Comment by mateoconlechuga** [comment] 2022-11-19 03:46
Why is every variable in this project a goddamn global

**Comment by mateoconlechuga** [comment] 2022-11-19 03:46
Why is every variable in this project a goddamn global

**Comment by Zaalan3** [comment] 2022-11-19 04:12
Blame Doom. Level, image and player data are referenced all over the place.

**Comment by mateoconlechuga** [comment] 2023-09-13 04:18
Closing as a potential duplicate of #426

**Comment by mateoconlechuga** [comment] 2023-11-17 20:45
Reopended just to confirm the potential duplicate is actually a duplicate

**Comment by adriweb** [comment] 2023-11-17 21:12
Just tried and confirmed, no more crashes, it builds correctly in all optimization levels!

**Closed by adriweb** 2023-11-17 21:12 UTC
Labels: bug, duplicate, compiler
