### ISSUE TITLE
int32_t's don't print properly outside 24 bits

### ISSUE THREAD

**Issue by fundudeone** [CE-Programming/toolchain#391] opened 2022-07-30 06:29 UTC
When using dbg_printf() with %li text will become garbled when the value cannot be represented in 24 bits.

Can be reproduced with:
```c
dbg_printf("attempting to print -8388608: %li\n", -8388608);
dbg_printf("attempting to print -8388609: %li\n", -8388609);
```

**Comment by jacobly0** [comment] 2022-07-30 06:37
`-8388609` is an int literal, did you mean `-8388609l` for a long int literal?

**Comment by fundudeone** [comment] 2022-07-30 06:40
I changed it, still garbled however.
Console:
attempting to print -8388608: -8388608
attempting to print -8388609: -(-((*0'

**Comment by jacobly0** [comment] 2022-07-30 06:41
Can't reproduce, can you please provide an entire project, or at least compilable code with all compiler options...

**Comment by fundudeone** [comment] 2022-07-30 06:49
`#include <stdint.h>
#include <debug.h>
#include <keypadc.h>

int main(void)
{
	dbg_printf("attempting to print -8388608: %li\n", -8388608l);
	dbg_printf("attempting to print -8388609: %li\n", -8388609l);

	while (!kb_On);
    return 0;
}`
is able to reproduce the error standalone. How can I find my compiler information?

**Comment by jacobly0** [comment] 2022-07-30 06:59
Either a toolchain version or the output of `ez80-clang --version`.

**Comment by fundudeone** [comment] 2022-07-30 07:04
Version: v10.1
eZ80 clang info:
clang version 14.0.0 (https://github.com/jacobly0/llvm-project 56af4f86925b7eebf23dae240e0a77c64066179e)
Target: ez80
Thread model: posix
InstalledDir: C:\CEdev\bin

**Comment by adriweb** [comment] 2022-07-30 09:22
Well that's not too old.

Can you check if it still happens using this version of the compiler? https://github.com/jacobly0/llvm-project/suites/7443696124/artifacts/304561586

**Comment by fundudeone** [comment] 2022-07-30 09:34
Yep same result after replacing executable in bin folder.

**Comment by fundudeone** [comment] 2022-07-30 09:35
I should also mention that I've been having other weirdness with int32_t. Comparisons between two will often give incorrect results that seem to change across the 24 bit threshold, but that might just be my own code being weird.

**Comment by jacobly0** [comment] 2022-07-30 11:22
Amazingly this was fixed by the last merge with upstream, so it will probably be a while until it is tested enough for a release, but you can download the nightly toolchain in the meantime.

**Closed by jacobly0** 2022-07-30 11:22 UTC
Labels: question
