### ISSUE TITLE
Debug target: not enough memory to complete the assembly.

### ISSUE THREAD

**Issue by hypothermic** [CE-Programming/toolchain#176] opened 2018-11-22 20:53 UTC
Compiling with default target works excellent:
```shell
raven@enforcer:~/proj/tifx$ make && make clean
C CE SDK Version 8.2
Z:\home\raven\proj\tifx\tifx\main.c
flat assembler  version g.i29v6-ez80
7 passes, 0.9 seconds, 1538 bytes.

Input File: Ti-FX.bin
--------------------
Output File: [TI-FX] Ti-FX.8xp
Archived: No
Size: 1538 bytes
--------------------
Success!

Cleaned build files.
```
However, compiling with `debug` target crashes even though I have enough memory availible (see below).
```shell
raven@enforcer:~/proj/tifx$ make debug && make clean
C CE SDK Version 8.2
Z:\home\raven\proj\tifx\tifx\main.c
flat assembler  version g.i29v6-ez80
Error: not enough memory to complete the assembly.
/home/raven/CEdev/include/.makefile:207: recipe for target 'bin/Ti-FX.bin' failed
make: *** [bin/Ti-FX.bin] Error 3
raven@enforcer:~/proj/tifx$
```
Here's the RAM usage graph from gnome-system-monitor:
![screenshot from 2018-11-22 21-49-16](https://user-images.githubusercontent.com/32428346/48921583-f527bb80-eea0-11e8-8c5c-123a37785250.png)

Any idea what's causing it?

**Comment by mateoconlechuga** [comment] 2018-11-22 20:54
Do you have a link to the project you are trying to compile?

**Comment by hypothermic** [comment] 2018-11-22 20:56
https://github.com/hypothermic/tifx

**Comment by mateoconlechuga** [comment] 2018-11-22 20:58
With the latest toolchain (8.5), a different error is produced:

```
ld.fasmg [760] macro ? [637] macro handle [5] macro parse [303] obj/main.src [690]:
	.BEGFUNC 'tifx_activity_new',21,'_tifx_activity_new'
macro ? [2] macro BEGFUNC [8] macro uleb128 [4]:
	assert val >= 0
Processed: assert val >= 0
Error: assertion failed.
```

We'll take a look and see what the issue is within the next couple of days :)

**Comment by mateoconlechuga** [comment] 2018-11-22 21:10
I would just like to point out that it is rather unsafe and technically "bad" practice to be putting code in header files. Code should be placed only in .c, or source files. This prevents recursive inclusion by the compiler. Not sure if this is related, but I would suggest you fix this before releasing :)

**Comment by hypothermic** [comment] 2018-11-22 21:17
I'm fairly new to C, coming from enterprise Java development. The code is horribly messy but I'll improve it along the way. Thanks for the tip.

**Comment by mateoconlechuga** [comment] 2018-11-23 03:38
I have submitted a Pull Request to your repository that fixes some issues and closes this issue, available here: https://github.com/hypothermic/tifx/pull/1

Be sure to download the latest toolchain (8.5) as well :) Thanks for the report, I'm going to close this for now however it might be worthwhile for @jacobly0 to take a look into what was causing it in the future.

**Closed by mateoconlechuga** 2018-11-23 03:38 UTC
Labels: bug

**Comment by jacobly0** [comment] 2018-11-23 05:29
The debug mode error is caused by zds not outputting enough debug info to support having code inside an `#include`.  Since this is not something you should be doing in the first place (because it causes linker errors if you try to include the file from more than one place (even with header guards!), which is the whole point of using `#include` in the first place) and even if I try to fix the issue it will just cause the C debugger to behave incorrectly, and on top of that, there's no way to detect this issue in all cases unless it happens to trigger this error, I'm keeping things how they are as it seems to be the least bad option for the time being.
