### ISSUE TITLE
ez80cc crashes under Windows 7 x64

### ISSUE THREAD

**Issue by elfprince13** [CE-Programming/toolchain#3] opened 2016-02-04 20:14 UTC
Executing ez80cc.exe from the bin directory, either directly, or through the makefile results in one of Windows "This program has stopped working" dialogs with the following problem details:

> Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	ez80cc.exe
  Application Version:	0.0.0.0
  Application Timestamp:	4ee77814
  Fault Module Name:	StackHash_0a93
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	65644543
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a93
  Additional Information 2:	0a93d4dc8b52e4293c6412941ec699fe
  Additional Information 3:	a466
  Additional Information 4:	a46638d0902048a75b3c1538b3e88c07

**Comment by adriweb** [comment] 2016-02-04 20:31
Probably duplicate of #5.

Closing for now, re-open if needed.

**Closed by adriweb** 2016-02-04 20:31 UTC
Labels: duplicate
