### ISSUE TITLE
Linker is unsupported on ARM

### ISSUE THREAD

**Issue by Bon-saiGecko** [CE-Programming/toolchain#324] opened 2021-08-13 21:36 UTC
Attempting to run `make` on an ARM device, such as an M1 MacBook Pro, will result in the following error. This issue occurs both with and without Rosetta 2. 

```
[linking] bin/DEMO.bin
Error: not enough memory to complete the assembly.
make: *** [bin/DEMO.bin] Error 3
```

**Comment by mateoconlechuga** [comment] 2021-08-15 16:45
This is caused by a bug in the x86 emulation on the M1 processor.
It would be nice to have a portable version of fasmg, but the feasibility of this requires a ton of work.

**Comment by mateoconlechuga** [comment] 2022-02-04 02:53
For now, this solution might be sufficient: https://ce-programming.github.io/toolchain/master/static/faq.html#how-can-i-use-fasmg-on-a-non-x86-processor

Closing for now until we have more issues with this.

**Closed by mateoconlechuga** 2022-02-04 02:53 UTC
Labels: external issue
