### ISSUE TITLE
ez80cc crashes under OS X 10.11 with both Wine 1.6 and 1.8

### ISSUE THREAD

**Issue by elfprince13** [CE-Programming/toolchain#5] opened 2016-02-04 20:21 UTC
> [thomas@Mithlond] ScanLineRender $ wineconsole ../toolchain/CEdev/bin/ez80cc.exe
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:advapi:RegisterTraceGuidsW (0x100778a, 0x100a060, {485e7de8-0a80-11d8-ad15-505054503030}, 1, 0x33fe40, (null), (null), 0x100a068,): stub
fixme:advapi:RegisterTraceGuidsW (0x100778a, 0x100a080, {485e7de9-0a80-11d8-ad15-505054503030}, 1, 0x33fe40, (null), (null), 0x100a088,): stub
fixme:advapi:RegisterTraceGuidsW (0x100778a, 0x100a0a0, {485e7dea-0a80-11d8-ad15-505054503030}, 1, 0x33fe40, (null), (null), 0x100a0a8,): stub
fixme:advapi:RegisterTraceGuidsW (0x100778a, 0x100a0c0, {485e7deb-0a80-11d8-ad15-505054503030}, 1, 0x33fe40, (null), (null), 0x100a0c8,): stub
fixme:advapi:RegisterTraceGuidsW (0x100778a, 0x100a0e0, {485e7dec-0a80-11d8-ad15-505054503030}, 1, 0x33fe40, (null), (null), 0x100a0e8,): stub
fixme:advapi:RegisterTraceGuidsW (0x100778a, 0x100a100, {485e7ded-0a80-11d8-ad15-505054503030}, 1, 0x33fe40, (null), (null), 0x100a108,): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x170f00, filter=0x53f56c,flags=0x00000001) returns a fake device notification handle!
wine: Unhandled page fault on read access to 0x45435c6e at address 0x45435c6e (thread 0031), starting debugger...
[thomas@Mithlond] ScanLineRender $ wine ../toolchain/CEdev/bin/ez80cc.exe
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:advapi:RegisterTraceGuidsW (0x100778a, 0x100a060, {485e7de8-0a80-11d8-ad15-505054503030}, 1, 0x33fe40, (null), (null), 0x100a068,): stub
fixme:advapi:RegisterTraceGuidsW (0x100778a, 0x100a080, {485e7de9-0a80-11d8-ad15-505054503030}, 1, 0x33fe40, (null), (null), 0x100a088,): stub
fixme:advapi:RegisterTraceGuidsW (0x100778a, 0x100a0a0, {485e7dea-0a80-11d8-ad15-505054503030}, 1, 0x33fe40, (null), (null), 0x100a0a8,): stub
fixme:advapi:RegisterTraceGuidsW (0x100778a, 0x100a0c0, {485e7deb-0a80-11d8-ad15-505054503030}, 1, 0x33fe40, (null), (null), 0x100a0c8,): stub
fixme:advapi:RegisterTraceGuidsW (0x100778a, 0x100a0e0, {485e7dec-0a80-11d8-ad15-505054503030}, 1, 0x33fe40, (null), (null), 0x100a0e8,): stub
fixme:advapi:RegisterTraceGuidsW (0x100778a, 0x100a100, {485e7ded-0a80-11d8-ad15-505054503030}, 1, 0x33fe40, (null), (null), 0x100a108,): stub
fixme:win:RegisterDeviceNotificationW (hwnd=0x170f00, filter=0x53f56c,flags=0x00000001) returns a fake device notification handle!
wine: Unhandled page fault on read access to 0x45435c6e at address 0x45435c6e (thread 0009), starting debugger...
Unhandled exception: page fault on read access to 0x45435c6e in 32-bit code (0x45435c6e).
Register dump:
 CS:001b SS:0023 DS:0023 ES:0023 FS:1007 GS:000f
 EIP:45435c6e ESP:0032f96c EBP:0032fed0 EFLAGS:00010202(  R- --  I   - - - )
 EAX:00000001 EBX:00000000 ECX:ffff0000 EDX:00010000
 ESI:00000001 EDI:00530e70
Stack dump:
0x0032f96c:  5c766564 5c6e6962 30387a65 632e6363
0x0032f97c:  02006e6f 02100210 02100210 02100210
0x0032f98c:  02100210 02100210 02100210 02840284
0x0032f99c:  02840284 02840284 02840284 02840284
0x0032f9ac:  02100210 02100210 02100210 03810210
0x0032f9bc:  03810381 03810381 03010381 03010301
0200: sel=1007 base=7ffc0000 limit=00000fff 32-bit rw-
Backtrace:
=>0 0x45435c6e (0x0032fed0)
  1 0x7b846d7c in kernel32 (+0x36d7b) (0x0032fee8)
  2 0x7b8494fe in kernel32 (+0x394fd) (0x0032ff28)
  3 0x7bc5d35c (0x0032ff38)
  4 0x7bc5f501 (0x0032ffb8)
  5 0x7bc5d322 (0x0032ffd8)
  6 0x7bc3c879 (0x0032ffe8)
0x45435c6e: -- no code accessible --
Modules:
Module   Address         Debug info   Name (3 modules)
PE     400000-  417000   Deferred        ez80cc
PE   7b810000-7b9ad000   Export          kernel32
PE   7bc10000-7bc14000   Deferred        ntdll
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) D:\Documents\sc2.11_eclipse_workspace\Scanline-Rendering\ScanLineRender\toolchain\CEdev\bin\ez80cc.exe
   00000009    0 <==
0000000e services.exe
   00000027    0
   00000026    0
   0000001e    0
   00000018    0
   00000016    0
   00000014    0
   00000010    0
   0000000f    0
00000012 winedevice.exe
   0000001d    0
   00000019    0
   00000017    0
   00000013    0
0000001a plugplay.exe
   00000021    0
   00000020    0
   0000001b    0
00000022 wdfmgr.exe
   0000002d    0
   0000002c    0
   0000002b    0
   0000002a    0
   00000028    0
   00000023    0
00000024 explorer.exe
   0000002e    0
   00000025    0

**Comment by adriweb** [comment] 2016-02-04 20:26
On OS X for me, wine 1.8 : Crashes for me if the folder has a relatively long length (> 100 chars?). No problem anymore when moved closer to the the FS root.
@jacobly0 and PT_ have been able to reproduce this as well.

Looks like an external issue, we can't do anything about it, so... move stuff around to have a shorter path, I guess.
Closing the issue.

**Closed by adriweb** 2016-02-04 20:26 UTC
