### ISSUE TITLE
Linker Bug (Probably related to missing long double support)

### ISSUE THREAD

**Issue by TheMiningTeamYT** [CE-Programming/toolchain#444] opened 2023-09-13 03:52 UTC
I've written some code and while trying to compile it, it got through the compiler stage but when linking I got the error
`Error: symbol ':globals.__dsub' is undefined or out of scope.`
and my brain melted because I have no idea what that means.
However, guessing by the "d" I'm guessing it's related to double/long double support, and I do use long doubles all over my code because I want maximum math precision for what I'm doing. And I do know reading through other issues that double/long double support has been a problem for some time now.
If this is that, then you can probably just close this issue. Otherwise, I'd like to get this fixed.
[error.txt](https://github.com/CE-Programming/toolchain/files/12593206/error.txt)

**Comment by mateoconlechuga** [comment] 2023-09-13 03:54
Can you either post the code here or send it privately so we can diagnose the issue please?

**Comment by mateoconlechuga** [comment] 2023-09-13 03:57
But yes, long double will most likely result in double functions attempting to be linked in. Also, if you read this: https://ce-programming.github.io/toolchain/static/hardware.html#floating-point-numbers

You may note that `float` and `double` have the same precision. If you want better precision, it is recommended to instead use an arbitrary-precision floating point library.

**Comment by runer112** [comment] 2023-09-13 04:00
If you want high precision, I'd suggest using TI's floating point type. There's a clunky C wrapper for it in _ti/real.h_ and a sleek C++ wrapper for it in _ti/real_.

**Comment by TheMiningTeamYT** [comment] 2023-09-13 04:02
That was fast.
This _should_ be everything you need. Let me know if you need anything else.
Please forgive my bad code. I'm not used to dealing with c strings and I'm not very good at planning out or adding comments to my code.
(btw, if you know of any good arbitrary precision math libraries for this, let me know, in the meantime I'll look into what runer112 mentioned)
[convert.zip](https://github.com/CE-Programming/toolchain/files/12593244/convert.zip)

**Comment by mateoconlechuga** [comment] 2023-09-13 04:05
Yeah it's confirmed that the compiler is emitting a call to `__dsub` (which is intended to be implemented or something). I'm going to mark it as a duplicate of #276 for now, but feel free to reopen if you have any other issues! It would be nice to get native support for these, but it's a little wild since it would be extremely inefficient.

**Closed** 2023-09-13 04:05 UTC
Labels: duplicate
